# Generated by Django 5.0.4 on 2026-10-06 13:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0004_productvariation_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Visualização de página"),
                            ("PRODUCT_VIEW", "Visualização de produto"),
                            ("ADD_TO_CART", "Adicionado ao carrinho"),
                            ("REMOVE_FROM_CART", "Removido do carrinho"),
                            ("CHECKOUT_STARTED", "Início do checkout"),
                            ("PURCHASE", "Compra"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "anonymous_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("path", models.CharField(blank=True, max_length=255)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_events",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_events",
                        to="products.productvariation",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="analytics_s_event_t_23b711_idx",
                    ),
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="analytics_s_user_id_b277a0_idx",
                    ),
                ],
            },
        ),
    ]
