# Generated by Django 5.0.4 on 2026-10-02 20:10

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0010_merge_20260916_2308"),
        ("products", "0007_product_rating_avg_product_rating_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purchased_size", models.CharField(blank=True, max_length=50)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000)),
                (
                    "fit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SMALL", "Pequeno"),
                            ("TRUE_TO_SIZE", "Certo"),
                            ("LARGE", "Grande"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PUBLISHED", "Publicada"), ("REMOVED", "Removida")],
                        default="PUBLISHED",
                        max_length=20,
                    ),
                ),
                (
                    "removal_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OFFENSIVE", "Linguagem ofensiva"),
                            ("SPAM", "Spam ou propaganda"),
                            ("PERSONAL_DATA", "Dados pessoais"),
                            ("OFF_TOPIC", "Não fala do produto"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("removal_note", models.TextField(blank=True, max_length=500)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_reply", models.TextField(blank=True, max_length=1000)),
                ("admin_reply_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "status", "-created_at"],
                        name="review_product_status_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(
                fields=("product", "user"), name="unique_review_per_user_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="review_rating_between_1_and_5",
            ),
        ),
    ]
