# Generated by Django 5.0.4 on 2026-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_seed_welcome_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorder",
            name="reservation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
