# Generated by Django 5.0.4 on 2026-09-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_checkoutattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="gateway_invoice_slug",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Not confirmed"),
                    ("PIX", "Pix"),
                    ("CREDIT_CARD", "Credit Card"),
                    ("BOLETO", "Boleto"),
                ],
                default="UNKNOWN",
                max_length=50,
            ),
        ),
    ]
