# Generated by Django 5.0.4 on 2026-09-11 19:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [("orders", "0004_checkoutattempt")]

    dependencies = [
        ("orders", "0007_shippingquote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("address_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("SUCCEEDED", "Succeeded"),
                            ("UNCERTAIN", "Uncertain"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("checkout_url", models.URLField(blank=True, max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkout_attempt",
                        to="orders.cart",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkout_attempt",
                        to="orders.customerorder",
                    ),
                ),
                (
                    "shipping_quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orders.shippingquote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="checkoutattempt",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"),
                name="checkout_attempt_user_key_unique",
            ),
        ),
    ]
