# Generated by Django 5.0.4 on 2026-10-07 22:31

import django.db.models.deletion
from django.db import migrations, models


def normalize_codes_and_flag_welcome_coupon(apps, schema_editor):
    """Prepara os dados antes das constraints novas.

    Normaliza os códigos existentes (a constraint passa a exigir maiúsculas,
    sem espaços) e transforma as regras fixas do BEMVINDO10 em dados.
    """
    Coupon = apps.get_model("orders", "Coupon")
    seen = {}
    for coupon in Coupon.objects.order_by("created_at"):
        code = "".join(coupon.code.split()).upper()
        if code in seen:
            raise RuntimeError(
                f"Os cupons {seen[code]!r} e {coupon.code!r} viram o mesmo código "
                f"{code!r} após a normalização. Renomeie um deles antes de migrar."
            )
        seen[code] = coupon.code
        if code != coupon.code:
            Coupon.objects.filter(pk=coupon.pk).update(code=code)

    Coupon.objects.filter(code="BEMVINDO10").update(
        first_purchase_only=True, auto_apply=True, max_uses_per_user=1
    )


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_payment_gateway_invoice_slug_alter_payment_method"),
        ("products", "0007_product_rating_avg_product_rating_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="auto_apply",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coupon",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="coupons", to="products.category"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="coupon",
            name="drops",
            field=models.ManyToManyField(
                blank=True, related_name="coupons", to="products.dropcampaign"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="first_purchase_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_discount_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_uses_per_user",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_uses_total",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_order_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="partner",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="coupon",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shippingquote",
            name="coupon_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.coupon",
            ),
        ),
        migrations.RunPython(
            normalize_codes_and_flag_welcome_coupon, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("code__regex", "^[A-Z0-9_-]+$")),
                name="coupon_code_normalized",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_value__gt", 0)),
                name="coupon_discount_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("discount_type", "PERCENTAGE"), _negated=True),
                    ("discount_value__lte", 100),
                    _connector="OR",
                ),
                name="coupon_percentage_at_most_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("max_discount_amount__isnull", True),
                    models.Q(
                        ("discount_type", "PERCENTAGE"), ("max_discount_amount__gt", 0)
                    ),
                    _connector="OR",
                ),
                name="coupon_max_discount_only_percentage",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("min_order_value__isnull", True),
                    ("min_order_value__gt", 0),
                    _connector="OR",
                ),
                name="coupon_min_order_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("starts_at__isnull", True),
                    ("expiration_date__isnull", True),
                    ("starts_at__lt", models.F("expiration_date")),
                    _connector="OR",
                ),
                name="coupon_starts_before_expiration",
            ),
        ),
    ]
