# Generated by Django 5.0.4 on 2026-09-13 13:36

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def migrate_catalog(apps, schema_editor):
    import re
    import uuid

    Variation = apps.get_model("products", "ProductVariation")
    Movement = apps.get_model("products", "StockMovement")
    Opening = apps.get_model("products", "StockOpeningBalance")
    Product = apps.get_model("products", "Product")
    alias = schema_editor.connection.alias
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "LOCK TABLE products_product, products_productvariation, products_stockmovement IN ACCESS EXCLUSIVE MODE"
        )
    normalized, combinations, skus, errors = [], {}, {}, []
    for v in Variation.objects.using(alias).all().order_by("pk"):
        size = " ".join(v.size.split()) or "Único"
        if size.casefold() in ("unico", "único"):
            size = "Único"
        color = " ".join(v.color.split())
        if color.startswith("#"):
            color = color.upper()
        sku = v.sku.strip().upper()
        key = (v.product_id, size.casefold(), color.casefold())
        if key in combinations or sku in skus:
            errors.append(
                f"{v.pk}: combinação/SKU colide com {combinations.get(key) or skus.get(sku)}"
            )
        if not re.fullmatch(r"[A-Z0-9_-]{1,100}", sku) or (
            color.startswith("#") and not re.fullmatch(r"#[0-9A-F]{6}", color)
        ):
            errors.append(
                f"{v.pk}: SKU/cor fora do contrato; corrigir administrativamente"
            )
        combinations[key], skus[sku] = v.pk, v.pk
        normalized.append((v, size, color, sku))
    for v, size, color, sku in normalized:
        if (
            size == "Único"
            and not color
            and sum(x.product_id == v.product_id for x, *_ in normalized) > 1
        ):
            errors.append(f"{v.pk}: variação padrão coexiste com variações reais")
    if errors:
        raise RuntimeError("Corrija o catálogo antes de migrar:\n" + "\n".join(errors))
    for v, size, color, sku in normalized:
        Variation.objects.using(alias).filter(pk=v.pk).update(
            size=size, color=color, sku=sku
        )
        Opening.objects.using(alias).create(variation_id=v.pk, balance=v.stock_quantity)
    for p in Product.objects.using(alias).filter(variations__isnull=True):
        Variation.objects.using(alias).create(
            product_id=p.pk,
            size="Único",
            color="",
            sku=f"SH-{uuid.uuid4().hex.upper()}",
            stock_quantity=0,
        )
    for m in Movement.objects.using(alias).all().iterator():
        Movement.objects.using(alias).filter(pk=m.pk).update(
            is_legacy=True,
            balance_after=None,
            origin_type="LEGACY",
            origin_id=m.pk,
            idempotency_key=f"legacy:{m.pk}",
        )

    if schema_editor.connection.vendor == "postgresql":
        # Conclui os eventos de FK gerados pelos dados antes de criar índices.
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")
        schema_editor.execute("SET CONSTRAINTS ALL DEFERRED")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderstatuslog"),
        ("products", "0004_productvariation_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="stockmovement",
            options={"ordering": ["-created_at", "-sequence"]},
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="promo_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="promo_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="promotional_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="balance_after",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="idempotency_key",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="is_legacy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="orders.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="origin_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="origin_type",
            field=models.CharField(
                choices=[
                    ("INITIAL_STOCK", "INITIAL_STOCK"),
                    ("MANUAL_ADJUSTMENT", "MANUAL_ADJUSTMENT"),
                    ("ORDER", "ORDER"),
                    ("LEGACY", "LEGACY"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="reverses_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compensation",
                to="products.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="sequence",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("ESTOQUE_INICIAL", "Estoque inicial"),
                    ("COMPRA", "Compra"),
                    ("DEVOLUCAO", "Devolução"),
                    ("AJUSTE", "Ajuste"),
                    ("PERDA", "Perda/Avaria"),
                    ("VENDA", "Venda"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="products.productvariation",
            ),
        ),
        migrations.AddField(
            model_name="stockopeningbalance",
            name="variation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opening_balance",
                to="products.productvariation",
            ),
        ),
        migrations.RunPython(migrate_catalog, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="stockmovement", name="origin_id", field=models.UUIDField()
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="origin_type",
            field=models.CharField(
                max_length=30,
                choices=[
                    (v, v)
                    for v in ("INITIAL_STOCK", "MANUAL_ADJUSTMENT", "ORDER", "LEGACY")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="idempotency_key",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddConstraint(
            model_name="productvariation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("size"),
                django.db.models.functions.text.Lower("color"),
                models.F("product"),
                name="unique_product_size_color",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("sku"),
                name="unique_normalized_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                fields=("variation", "sequence"), name="unique_stock_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_legacy", True),
                    models.Q(
                        ("balance_after__isnull", False),
                        ("sequence__isnull", False),
                        ("quantity__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="stock_audited_balance",
            ),
        ),
    ]
