# Generated by Django 5.0.4 on 2026-10-02 20:10

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_normalize_variation_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_avg",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
